apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nfi2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nfi2
    app.kubernetes.io/part-of: ci10t-777-0088-app
  name: devfile-sample-nfi2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nfi2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nfi2
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0088-tenant/ci10t-777-0088-app/devfile-sample-nfi2@sha256:b5c010fd04c08df9beaa4373b43b1b703ca0d9313cada775e8b17f828ea7a5be
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
